from __future__ import annotations
import sys
from mindsos_arc import capacities as ac

BUNDLE_NAME = "arc"
BUNDLE_VERSION = "0.1.0"
REQUIRES_PHASE = 50  # Phase-50 install lifecycle (ADR-0183); realms/edges all present

dss = sorted(d.iri for d in ac.arc_datastates())
caps = sorted(c.iri for c in ac._all_capacities())

def toml_list(items, indent="  "):
    if not items:
        return "[]"
    body = ",\n".join(f'{indent}"{i}"' for i in items)
    return "[\n" + body + ",\n]"

out = []
out.append("# GENERATED by gen_manifest.py from install_arc's live catalog.")
out.append("# Regenerate on any capacity/datastate change; parity test guards drift.")
out.append("")
out.append("[bundle]")
out.append(f'name = "{BUNDLE_NAME}"')
out.append(f'version = "{BUNDLE_VERSION}"')
out.append(f"requires_mindsos_phase = {REQUIRES_PHASE}")
out.append("requires_bundles = []")
out.append("")
out.append("# [l2] — empty at v1 (ARC caps/datastates reactivate from code; no L2 content)")
out.append("# [l4] — empty at v1")
out.append("")
out.append("[l3]")
out.append(f'installers = ["mindsos_arc.capacities:install_arc"]')
out.append(f'allow_new_realm = ["arc"]')
out.append("capacities = " + toml_list(caps))
out.append("datastates = " + toml_list(dss))
out.append("")
text = "\n".join(out)
open("mindsos_arc/bundle/manifest.toml", "w").write(text)
print(f"wrote manifest: {len(caps)} capacities, {len(dss)} datastates")
